### ISSUE TITLE
Allow other modded axes to debark logs.

### ISSUE THREAD

**Issue by MagmaSlime123** [asiekierka/Debark#20]

**Comment by asiekierka** [comment]
Other modded axes should correctly define a tool class of "axe".

**Comment by MagmaSlime123** [comment]
Which most don't.

**Comment by asiekierka** [comment]
So they should fix it, or a patch mod should be created to fix it for them. That's the Forge standard for 1.12 (for any item extending ItemAxe, it's done by default), and I'm not particularly interested in making exceptions for other mods' axes on my side - especially if such a patch could fix compatibility problems more broadly.
