### ISSUE TITLE
[Feature Request] Bark Drop

### ISSUE THREAD

**Issue by VinterNacht** [asiekierka/Debark#3]
I would love to have the option for this mod to return a bark object when debarking a log.

**Comment by supersaiyansubtlety** [comment]
I would also appreciate this feature

**Comment by gswindle76** [comment]
Please add this. This would be a HUGE gap fix between Better With Mods and Forestry Farms.  Forestry simulates "Punching" trees to break.  But certain packs require BWM bark to tan leather ( Engineers Life for example ). However, BWM does not drop logs just bark/planks/sawdust.   Forestry farms us "punching" to automate trees, and prevents them from automating logs.
