### ISSUE TITLE
Texture Issue w/ Lithos Resource Pack

### ISSUE THREAD

**Issue by nephatrine** [asiekierka/Debark#7]
These logs are fantastic when using vanilla textures, but if I switch to Lithos, I get weird black areas on the logs:

https://imgur.com/a/O7uGVbg

Any idea what the cause could be? How are the textures generated? Is it because they are 32x and not 16x?

**Comment by CipheredEntity** [comment]
I'm having the exact same issue with PureBDcraft 128x Texture Pack. Except the side textures are condensed even further into just tiny slivers, With the vast majority of the side texture being black. Definitely some issue involving texture packs with higher resolution then 16x. Just wish I knew how to fix it, if it's possible to fix.
<img width="1680" alt="Screen Shot 2019-11-26 at 2 19 05 AM" src="https://user-images.githubusercontent.com/54157567/69607662-b5376f00-0ff3-11ea-9085-b52ee87335b7.png">

**Comment by nephatrine** [comment]
I'm not able to check at the moment, but I wonder if replacing Debark's textures (debark:blocks/debark_top_minecraft_log_0.png, debark:blocks/debark_side_minecraft_log_0.png) with ones just resized to match the texture pack size would have any effect.

**Comment by asiekierka** [comment]
That should be correct - as documented on the mod's CurseForge page.
I'll look into fixing this eventually. A bit low on time at the moment.

**Comment by asiekierka** [comment]
Fixed in 0.1.2.
